version: '3.9'
services:
  web:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - ${APP_PORT}:3000
    networks:
      - default
    volumes:
      - data:/data

networks:
  default:
    name: docker_grafana_network
    driver: bridge

volumes:
  data:
    name: docker_grafana_data
    driver: local
